<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <PackageTags>NuGet</PackageTags>
    <Description>BaGetter's NuGet server implementation</Description>
    <RootNamespace>BaGetter.Web</RootNamespace>

  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaGetter.Core\BaGetter.Core.csproj" />
  </ItemGroup>

</Project>
